name: Deploy to GitHub Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with: { node-version: '18' }
      - name: Install dependencies
        run: npm ci
      - name: Build and Deploy
        run: npm run deploy
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }